import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToggleProvider } from "@/components/context/ToggleContext";
import NavBar from "@/components/navBar/NavBar";
import SideBar from "@/components/sideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "/dashborad",
  description: "Generated by Imad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user: boolean = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToggleProvider>
          <main>
            <NavBar />
            <SideBar />
            {children}
          </main>
        </ToggleProvider>
      </body>
    </html>
  );
}
